# The name of the label to apply when an issue does not have all tasks checked
labelName:

# The color of the label in hex format (without #)
labelColor:

# The text of the comment to add to the issue in addition to the label
commentText: >
  Text here.
  More text here.
  And more text here.

# Whether or not to ensure all checkboxes are checked
checkCheckboxes: true  

keywords:
  - gist
  - recreate